### PR TITLE
feat: add rpt2 prefix to remaining errors

### LINKED ISSUE #300: add prefix to error messages to improve DX
https://github.com/ezolenko/rollup-plugin-typescript2/blob/4e9f8fff080072a90164590b399768ca21a4d4e0/src/parse-tsconfig.ts#L27

for this example, it could be like ```throw new Error(`rpt2: failed to read '${fileName}'`)```

if you allow, i can provide a pull request later, covering the whole project.

### PR DESCRIPTION
**Pull request by agilgur5**
## Summary

Add `rpt2: ` prefix to remaining, unprefixed error messages
- Fixes #300

## Details

- most were added in ff8895103c8466694e7d8eeb734f51d2850670d8, but these two were missed

- this should now cover all **thrown** errors
  - they only get thrown in the [`options`](https://rollupjs.org/guide/en/#options) hook, which does not implement Rollup's `this.error`
  - all other errors are already auto-prefixed by RollupContext etc

### CODE REVIEW

**Comment by agilgur5** [comment]
Tests are failing due to #377 ; the ones that check these error messages pass
