### PR TITLE
improve dependencies

### PR DESCRIPTION
**Pull request by lmk123**
After I upgrade to v0.6.0, it show me an error:

```
Error: Cannot find module 'rollup-pluginutils'
```

So I move `rollup-pluginutils` to _dependencies_.

BTW I add `typescript` and `rollup` to _peerDependencies_, so if user doesn't install it(or version incompatible), NPM will show a tip in console.

### CODE REVIEW

**Comment by ezolenko** [comment]
Ah, looks like I was overly enthusiastic when cleaning up dependencies. Thanks.
