### ISSUE TITLE
`microbundle` doesn't support TS 4.1 `react-jsx` config

### ISSUE THREAD

**Issue by thebiltheory** [ezolenko/rollup-plugin-typescript2#255]
React 17 ships with a new JSX transform which causes errors during the compilation with Microbundle.
For those who upgraded, `react-scripts` changes automatically your `tsconfig` to `jsx: 'react-jsx'` which isn't yet supported by this plugin. 

See https://github.com/developit/microbundle/issues/763

Is there any plan yet to upgrade this plugin to `version 4.1`?
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#jsx-factories

**Comment by ezolenko** [comment]
The plugin itself builds fine with ts 4.1, looks like there is something happening with jsx option?

Could you set plugin verbosity to 3 and post the output (it will print out parsed tsconfig and versions of related apps)

**Comment by johngarcia9110** [comment]
I am also getting this error.

`rpt2: config error TS6046: Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.`

**Comment by agilgur5** [comment]
Per https://github.com/developit/microbundle/issues/763#issuecomment-747802462 `microbundle` maintainers stated it was indeed on their side and that they had erroneously pointed at rpt2 before.
rpt2 does not pin a TS version and just lists it as a peerDep, so when using rpt2 _directly_, it should use the same TS version you have installed.

https://github.com/developit/microbundle/pull/741 changed their TS import resolution a bit to try to grab the TS you have installed as well.

In any case, the issue was downstream in `microbundle`, and not here. As such, will be closing due to that as well as the fact that OP had not responded to further requests for comment.

If you believe this is still an issue, please provide a minimal reproduction with rpt2's latest version showing this issue either here or in a new issue for us to investigate.
